### ISSUE TITLE
argument parsing

### ISSUE THREAD

**Issue by durka** [Xion/cargo-contribute#1]
Looks like your binary doesn't recognize the first argument always being "contribute", which it is when called as a cargo subcommand (but not if you just do e.g. `./target/debug/cargo-contribute`).

```
$ cargo contribute
error: Found argument 'contribute' which wasn't expected, or isn't valid in this context

USAGE:
    cargo contribute [OPTIONS]

For more information try --help
$ cargo-contribute
[works]
```

**Comment by Xion** [comment]
Whoa, that's a really nasty gotcha! I wasn't aware that Cargo isn't passing argv correctly to subcommand; isn't that a bug in Cargo?

In any case, I should be testing it with a `~/.cargo/bin` symlink :/ I fixed the issue though and prepared a new release.

**Comment by durka** [comment]
I don't know if it's a bug or not. I think Cargo just invokes the subcommand transferring all of argv, so the first argument is still "contribute". I guess you could write a meta-subcommand that is one binary but changes behavior based on which subcommand you invoke it as (like busybox), so you'd need that argument for dispatch.

**Comment by Xion** [comment]
I think it also helps when the parsing is done via docopt, because there you want to formulate the usage string with `cargo foo`, causing docopt to expect `foo` as part of the command line.

Either way, thanks again for spotting this!
